version: '3'

services:
  was:
    container_name: url-shortener
    build:
      context: .
    command: /app/run.sh
    ports:
      - 80:5000
    environment:
      - FLASK_APP=src/http/app.py
      - URL_SHORTENER_PG_URI
